#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
Written by Gábor Erdős, 2017
Contact info: gerdos[at]caesar.elte.hu

The preferences were calculated from the following artice:
Lovell et al. Structure validation by Calpha geometry: phi,psi and Cbeta deviation. 2003
DOI: 10.1002/prot.10286
"""

import sys
from pyrama import calc_ramachandran, plot_ramachandran
if len(sys.argv) < 2:
    sys.exit("Usage: pyrama my_pdb_file.pdb")

normals, outliers = calc_ramachandran(sys.argv[1:])

pdb_size = len(normals.get('General').get('x')) + \
           len(normals.get('GLY').get('x')) +\
           len(normals.get('PRO').get('x')) +\
           len(normals.get('PRE-PRO').get('x'))

out_size = len(outliers.get('General').get('x')) + \
           len(outliers.get('GLY').get('x')) +\
           len(outliers.get('PRO').get('x')) +\
           len(outliers.get('PRE-PRO').get('x'))

print('%d:%d:%f'%(out_size,pdb_size,out_size/pdb_size))

#print(len(normals.get('General').get('x')))
#print(outliers)
#plot_ramachandran(normals, outliers)

